### ISSUE TITLE
Code OSS cannot activate extension after update to 0.5.4

### ISSUE THREAD

**Issue by RB-Lab** [meganrogge/template-string-converter#59]
Hello! First of all, this is really must have extension, thanks for creating it!

After update to version `0.5.4` the extension just stops working. After some couple of times reinstalling extension, I've notice the tab "Runtime Status", and on it it was said "Not yet activated". After quite some more time, I've found the "Log (Extension Host)" sections in logs panel and there was error:
```
[2021-12-08 12:31:54.295] [exthost] [error] Activating extension meganrogge.template-string-converter failed due to an error:
[2021-12-08 12:31:54.295] [exthost] [error] Error: Cannot find module '/home/user/.vscode-oss/extensions/meganrogge.template-string-converter-0.5.4/out/extension.js'
```
I went in the extension folder and found that in `packge.json`  it is said: `"main": "./out/extension.js"`. However there is no folder named `out`.  But there is a file, named `launch.json` and in it there is a string:
```json
"outFiles": ["${workspaceFolder}/dist/web/**/*.js"],
```
So, I've just copied all contend contend of `dir/web` into newly created `out` directory and everything looks to be working now. 

I'm not familiar with Code extension publishing process, but it looks like something went wrong somewhere in it. Maybe it is due to my **Code version**, which is **1.62.0**, or maybe it somehow related to the fact that in Arch's Linux Code uses different marketplace: [Open VSX Registry](https://open-vsx.org/extension/meganrogge/template-string-converter).

**Comment by meganrogge** [comment]
Hey thanks so much for this report and info. Can you try updating to version 0.5.5? It's working for me in that version.

**Comment by meganrogge** [comment]
![recording - 2021-12-08T085109 400](https://user-images.githubusercontent.com/29464607/145249302-9db1f27c-d0ca-4f10-8a7a-e5b87d6675b8.gif)

**Comment by RB-Lab** [comment]
Emm.. is it available? In my repo it seems that 0.5.4 is the latest version:
![image](https://user-images.githubusercontent.com/5694678/145281063-c42a27d3-8d5f-4366-9b5d-b6bc21caea29.png)
And here on GitHub [it seems to be the same](https://github.com/meganrogge/template-string-converter/blob/master/package-lock.json#L3).

**Comment by meganrogge** [comment]
it says version 0.5.5 is available in the marketplace https://marketplace.visualstudio.com/items?itemName=meganrogge.template-string-converter

**Comment by meganrogge** [comment]
also just tried rolling back to 0.5.4 and wasn't seeing the problem you describe there either.

**Comment by RB-Lab** [comment]
Hm. Yeah, just downloaded 0.5.4 from VisualStudio Marketplace and there `out` folder is in place. Seem to be OpenVSX problem.

**Comment by RB-Lab** [comment]
Ahh, damn, it's not even you who published the extension there! 
![image](https://user-images.githubusercontent.com/5694678/145398788-f094f99d-3e72-4444-82e0-102bcb1624aa.png)
Ok. I'll address this issue to open-vsx than.

**Comment by filiptronicek** [comment]
It looks like the `out/` directory gets no longer generated, webpack outputs its results to `dist/`. 

This is the result after packaging with `vsce`:
![image](https://user-images.githubusercontent.com/29888641/145831806-e96fdb4d-e536-435c-bfaf-5c4313e86e37.png)

@meganrogge it looks like the wrong paths are here, or am I missing something? https://github.com/meganrogge/template-string-converter/blob/d8144523a57aeb6e16dd6e81fd9ec750fcb08ad2/package.json#L23-L25

**Comment by meganrogge** [comment]
I made this web-enabled, which is why there is that browser entry there. If you remove that and replace the scripts with:

```
"scripts": {
    "vscode:prepublish": "npm run compile",
    "compile": "tsc -p ./",
    "watch": "tsc -watch -p ./",
    "package-web": "eslint . --ext .ts,.tsx"
  },
```
it will work
